### ISSUE TITLE
ModuleNotFoundError: No module named 'crispy_forms'

### ISSUE THREAD

**Issue by Abhikarom** [harshd23/Attendance_System_using_Face_Recognition#1]
Kindly help me with this error

**Comment by harshd23** [comment]
Please Install Python **[3.8.10 version](https://www.python.org/downloads/release/python-3810/)** then follow the below steps:

1) Create a virtual environment. 
`virtualenv environment-name`

2) Activate the virtual environment.
`./environment-name/Scripts/activate`

3) Install the libraries using the requirements.txt
`python -m pip install -r .\requirements.txt`

**Comment by Abhikarom** [comment]
It would be of great help If you create a video tutorial on how to run this project including creating virtual environments. I am still not able to run this.
Thank you

**Comment by harshd23** [comment]
Please do check the steps which are mentioned [here](https://github.com/harshd23/Attendance_System_using_Face_Recognition#steps-to-run-this-application-), I have listed steps to run the project smoothly.

**Note:** When you clone the project, the later step is to create virtual environment, install the required libraries and it is always necessary to activate the environment before running the project.

Here some resource about virtual environment, which might be of great help: 
* [https://youtu.be/uAiapBnFsKs](https://youtu.be/uAiapBnFsKs)
* [https://www.freecodecamp.org/news/how-to-setup-virtual-environments-in-python/](https://www.freecodecamp.org/news/how-to-setup-virtual-environments-in-python/)

**Comment by Abhikarom** [comment]
![Windows PowerShell 29_06_2023 14_19_53](https://github.com/harshd23/Attendance_System_using_Face_Recognition/assets/137608725/c39be87f-4a36-42c9-97ec-76c9aceffeeb) 
What should I do now?   I have created virtual environment and also activated it.. Kindly help me

**Comment by Abhikarom** [comment]
![Windows PowerShell 29_06_2023 14_26_32](https://github.com/harshd23/Attendance_System_using_Face_Recognition/assets/137608725/c62f55d6-ee92-4bc4-8d95-937c48a4b5f8)

I am doing this as my final year project.. So kindly help me.... can I contact you to get these things done?

**Comment by harshd23** [comment]
Please check for the directory and folder structure. Run the commands where the manage.py file is present.
